[package]
name = "tinyraycaster"
version = "0.1.0"
authors = ["Igoru <fuzzyqu@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
codegen-units = 1

[dependencies]
